version: '3.8'

networks:
  nestjs-kong-poc:
    name: 'nestjs-kong-poc'

services:
  app_dev:
    container_name: app
    working_dir: /app
    command: sh -c "npm run start:dev"
    build:
      context: .
      args:
        BUILD_STAGE: development
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - .:/app
    networks:
      - nestjs-kong-poc

  app_prod:
    container_name: app
    build:
      context: .
    ports:
      - '${PORT:-3000}:3000'
    networks:
      - nestjs-kong-poc

  kong:
    container_name: kong
    image: kong/kong-gateway:3.5.0.2
    ports:
      - '8000:8000/tcp'
    volumes:
      - ./kong:/kong/declarative/
    env_file: .env
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_LOG_LEVEL: ${KONG_LOG_LEVEL:-error}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://kong:8000" ]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - nestjs-kong-poc
